<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>tfvm</AssemblyName>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<!--<ItemGroup>
		--><!-- Config esterna modificabile --><!--
		<Content Include="appsettings.json" CopyToPublishDirectory="Always" />
	</ItemGroup>-->

	<ItemGroup>
		<!-- Copia il file in output per debug e build -->
		<None Include="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<!-- Impedisce che venga incluso dentro il single-file -->
			<IncludeInSingleFile>false</IncludeInSingleFile>
		</None>
	</ItemGroup>


    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
        <PackageReference Include="System.CommandLine" Version="2.0.0" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\CodeLab.ToolManager.Pkg.Core\CodeLab.ToolManager.Pkg.Core.csproj" />
    </ItemGroup>

</Project>
